import type { Metadata } from "next";
import localFont from "next/font/local";
<<<<<<< HEAD
=======
import "./globals.css";
>>>>>>> 102c2bcc4a7a602030d98a6d3b3c1bf801954c49

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
<<<<<<< HEAD
  title: "YouTube",
  description: "YouTube Clone",
=======
  title: "Create Next App",
  description: "Generated by create next app",
>>>>>>> 102c2bcc4a7a602030d98a6d3b3c1bf801954c49
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
